### ISSUE TITLE
i18n: problem set 3, Clock Face - 1

### ISSUE THREAD

**Issue by A-Lawrence** [snakify/content#2]
The problem here states:

> H hours, M minutes and S seconds are passed since the midnight (0 ≤ H < 12, 0 ≤ M < 60, 0 ≤ S < 60). Determine the angle (in degrees) of the hour hand on the clock face right now.

However, tests don't actually expect the answer in _degrees_, they expect the answer in _decimal minutes and seconds_.  Happy to provide a PR to fix this either way, but I just want to clarify *before* I do that you don't actually mean degrees?

--

**If you mean degrees, then the following logic would hold true:**

15 minutes = 90 degrees
30 minutes = 180 degrees
45 minutes = 270 degrees
60/0 minutes = 360/0 degrees

Such that:
1 minute = 6 degrees

Resulting in:
30 seconds = 3 degrees
10 seconds = 1 degree
1 second = 0.1 degree

The resulting code would be:

```python
h = int(input())
m = int(input())
s = int(input())

print((m * 6) + (s * 0.1))
```

--

If you mean the decimal minutes and seconds, then the current tests are correct but I'll need to update the language within the question.

If you could clarify @vpavlenko / @goldvitaly, I'll happily PR this.

**Comment by A-Lawrence** [comment]
Ignore everything I wrote - it helps if one actually reads that it states hour hand!

**Comment by heeraadbahr** [comment]
Hi there, Actually it wants you to determine angle of hour hand from the start(00:00:00) so you need to calculate how many degrees the hour hand moved exactly ( you will understand what I mean in following):
each 12 hour passes the hour hand moves 360 degree. so each hour passes the hour hand moves 30 degrees..it is obvious
also each one hour has 60 minutes and each minute passes the hour hand moves ( 1/60 of that 30 degree)
and finally for the seconds ...each second passes, the hour hand moves(1/3600 of that degree)
so the answer will be
h = int ( input ( ) )
m = int ( input ( ) )
s = int ( input ( ) )
print ( ( 30 * h ) + ( 30 * m / 60 ) + ( 30 * s / 3600 ) )
