### ISSUE TITLE
Show wrong answer next to correct answer?

### ISSUE THREAD

**Issue by johnkershaw** [snakify/content#38]
When you scroll down to see the tests, it would be helpful to see the output from your program next to the Correct output. My student was doing the area of a right triangle exercise but didn't divide by 2. He saw the Correct answer was 7.5 but couldn't see that HIS answer was 15 (which would've clued him in to the solution).

BTW This is my first time using github for anything real, so apologies if I'm "doing it wrong". I've been a coder for 38 years (now a CS teacher in Cambodia) but back when I was coding commercially it was cvs - and not much of that!

**Comment by vpavlenko** [comment]
@johnkershaw Incidentally, we've just rolled out that feature :) Please, let me know if that works now.

**Comment by johnkershaw** [comment]
Yes, that's great!


M: +855 123 3 1948
