### ISSUE TITLE
"Next problem" link should be bigger/bolder/buttonier

### ISSUE THREAD

**Issue by johnkershaw** [snakify/content#41]
First time through I couldn't find this for ages. My first bunch of students had the same trouble.

If all the tests have passed the 'Next problem' should be a giant (green?) button. Or something.

![image](https://user-images.githubusercontent.com/5265410/38073543-bff52e22-3355-11e8-9dd4-6c9619d6ee12.png)

**Comment by vpavlenko** [comment]
@johnkershaw Thanks, we'll have it once we revise the design of this page.
